### ISSUE TITLE
Can't mount component: Element type is invalid: expected a string (for built-in components) or a class/function

### ISSUE THREAD

**Issue by graphee-gabriel** [microlinkhq/sdk#100]
Hello, when I try to mount a `<MicrolinkCard />` component, i get the following error:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

This is how i import it:
```
import React from 'react'
import MicrolinkCard from 'react-microlink'

const MyTestComponent = props => {
  return (
    <MicrolinkCard url={props.url} />
  )
}
```

I tried as well with `import * as MicrolinkCard from 'react-microlink'`
No success so far

**Comment by breadadams** [comment]
Hi @graphee-gabriel, could you try installing `styled-components` if you don't have it already?

```bash
npm install styled-components --save
```

We [recently](https://github.com/microlinkhq/sdk/commit/2e0aa3eb1ecf36e6354a67e4915314e63019e804) moved it to a peer dependency of this library, and therefore it won't be _automatically_ included in your `node_modules` on install.

**Comment by graphee-gabriel** [comment]
Hey @breadadams i had it already installed, following your documentation.
I re-installed to be sure with `npm install styled-components --save` but still same issue :-(

**Comment by Kikobeats** [comment]
hum what version of react and node are you using?

I installed it and it's working as expected 🤔

**Comment by breadadams** [comment]
Oh right, I'd forgot the docs had been updated accordingly 😅. Hmm, could you share a larger code example, maybe even a small reproduction site?

I notice in the snippet you posted there's no `export default MyTestComponent` @graphee-gabriel, I'm _guessing_ this is just from it being an example?

**Comment by graphee-gabriel** [comment]
Yes indeed! Here is the full code:

> import React, { Component } from 'react'
> import { storage } from '../firebase'
> import Linkify from 'react-linkify'
> import Colors from '../constants/Colors'
> 
> import TitleSmall from './TitleSmall'
> import MicrolinkCard from 'react-microlink'
> import { REGEX_URL } from '../constants/Regex'
> 
> class SubListItem extends Component {
>   state = {}
> 
>   componentWillMount() {
>     // need to fix MicrolinkCard
>     // issue here: https://github.com/microlinkhq/sdk/issues/100
>     // console.log('MicrolinkCard', MicrolinkCard)
>     this.onPropsChanged(this.props)
>   }
> 
>   componentWillUpdate(nextProps) {
>     this.onPropsChanged(nextProps)
>   }
> 
>   onPropsChanged = props => {
>     const { imageRef, description } = props
>     if (this.imageRef !== imageRef) {
>       this.imageRef = imageRef
>       storage.ref(imageRef).getDownloadURL().then(imageUrl => {
>         this.setState({ imageUrl })
>       })
>     }
>     if (this.description !== description) {
>       this.description = description
>       const matches = description.match(REGEX_URL)
>       const links = []
>       if (matches && matches.length > 0)
>         matches.forEach(link => {
>           if (link && link.length > 3 && links.indexOf(link) === -1)
>             links.push(link)
>         })
>       this.setState({ links })
>       // console.log('links found: ', links)
>     }
>   }
> 
>   render() {
>     return (
>       <SubListItemRender {...this.state} {...this.props} />
>     )
>   }
> }
> 
> const SubListItemRender = ({
>   title,
>   index,
>   description,
>   showDescription,
>   imageUrl,
>   style,
>   links,
>   ...props }) =>
>   <div style={{ ...styles.viewMain, ...style }}>
>     <TitleSmall style={styles.textTitle}>
>       {(index + 1) + '. ' + title}
>     </TitleSmall>
>     <div style={styles.viewDescription}>
>       <Linkify properties={{ target: '_blank' }}>
>         <div style={styles.textDescription}>
>           {description}
>         </div>
>       </Linkify>
>       {imageUrl != null && imageUrl !== '' && (
>         <a href={imageUrl} target="_blank">
>           <div style={styles.viewImage}>
>             <img style={styles.imgImage} src={imageUrl} />
>           </div>
>         </a>
>       )}
>       {false && links != null && links.length > 0 && ( 
>         <div style={styles.viewLinks}>
>           {links.map(link => <MicrolinkCard key={link} url={link} />)}
>         </div>
>       )}
>     </div>
>   </div>
> 
> 
> const styles = {
>   viewMain: {
>     borderRadius: 8,
>     borderStyle: 'solid',
>     borderWidth: 1,
>     borderColor: Colors.colorSeparator,
>     margin: 8
>     // flex: 1,
>     // display: 'flex',
>     // flexDirection: 'column',
>     // backgroundColor: Colors.colorGrayBackground,
>   },
>   textTitle: {
>     padding: 16,
>     // fontFamily: 'Raleway',
>     backgroundColor: Colors.colorSummaryTitleBackground,
>     borderTopLeftRadius: 8,
>     borderTopRightRadius: 8,
>   },
>   viewDescription: {
>     padding: 8,
>   },
>   textDescription: {
>     padding: 8,
>   },
>   viewImage: {
>     // borderRadius: 5,
>     // borderStyle: 'solid',
>     // borderWidth: 0,
>     // borderColor: 'transparent',
>     // overflow: 'hidden',
>     margin: 8,
>   },
>   imgImage: {
>     flex: 1,
>     maxWidth: '100%',
>     maxHeight: '100%',
>     width: 'auto',
>     height: 'auto',
>   }
> }
> 
> export default SubListItem

**Comment by breadadams** [comment]
No worries @graphee-gabriel, glad you resolved it! I'll close this for now, don't hesitate to open further issues if you run into any trouble 🙂
