### ISSUE TITLE
Prevent app crashing when rate limit exceeded

### ISSUE THREAD

**Issue by mikewheaton** [microlinkhq/sdk#119]
I hit the daily limit today and it caused the app to crash while using the `MicrolinkCard` React component:

![image](https://user-images.githubusercontent.com/1382445/43041274-1584232a-8d10-11e8-8c1b-724640909a6d.png)

It would be better to display a friendly message on the card about the limit being exceeded, perhaps with a link to the [pricing page](https://microlink.io/#pricing). Or have a missed a step in being able to handle this error and display alternate UI?

**Comment by Kikobeats** [comment]
It should be fixed in the current version 🙂
