### ISSUE TITLE
Microlinks is down

### ISSUE THREAD

**Issue by MohamedLamineAllal** [microlinkhq/sdk#130]
## Bug Report
The whole API is down, i come to try the react client for the first time, then after some time where everything work great a boom happen. Everything donwn. Here in the bookstore https://storybook.microlink.io/?selectedKind=media&selectedStory=image&full=0&addons=1&stories=1&panelRight=0&addonPanel=kadira%2Fjsx%2Fpanel is clear. 
(I don't know if this is because of some work you are doing or something else, i thought it will be nice to fill an issue so in any case you get to know).

An image:
![down](https://lh3.googleusercontent.com/1LCEvHM54v43WB8XZBq-amCbZYVaszrMdstQswFRZgLLS3dIMe1O57INtGDe2wZxKGHOcuXgnaFQ2e3ZMabUhaP15niVPoPlL6LE98jKjRLWsUkCt_eAZeRzL2qBu23OicQyvHACu3eoxOGQ-_iSGXQaWA2V2CKipj0Hy9Sz7nCADgmqviKJiyjjsiSvbxB9DMYy1j6-wk8xB5KRGEECKNOrbT68eMf_Zio1vsVmojmp0zeeIvzcq1RNeXvKI-DoTeZ-pk3hG-qRBnnF65d25VfsUY26PKH29b1r0E7FDWvSOrT00dpRO72ukYyexRlhyC7CFhWW57p5IOuhj6sElHX1fvaa-lNgEMssOLqyWNCnytMKGanFxvjagzS-FVam6oygZALLab_H7UX-rLZcnTsE_6cwxMPH2WO_wwn7phM6i2_fs0owjrdt11QfKkfCh0ymO1MFVMVabvAo_487E-6qwuJ02LFeFougPlGdxM1pDgaffT2sYQ9eBieVcMF7upgJXsyDLjl9EJ9c3zkv59_mnhhIFKCwSkygLTiq4lUFhb6IkHHAIRHyBzA06yaEnxUkJP894E9QBoI_b82Ops2RQhbl7B0-5sovaM5uF8lsv2pJ66-UqglUas1KRATmpP72jBWSO0qYhOKZxWhMfsWyzyCal8zbe21ieAcaMS7nuFF3YRmDI9saJZ-z6ZPJSYUQ-1cHNbZBcF2dyA=w1122-h897-no "Down")

**Comment by MohamedLamineAllal** [comment]
The problem seem to be with my computer, all browser the same, tested from my phone and it work fine, I think something wrong, there were no request to microlinks when debugged. I close the issue false alert

**Comment by Kikobeats** [comment]
Thanks for reporting!

We have multiple alarms for ensuring all services are up and working as expected.

You can see that reflected at https://status.microlink.io 🙂
