### ISSUE TITLE
Implement size mini

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/sdk#144]
![Screenshot 2019-04-28 at 12 13 38](https://user-images.githubusercontent.com/2096101/56862798-168c5680-69af-11e9-8e0c-a51ed65f44a6.png)

I was navigating and see [SoundCloud mini player](https://openai.com/blog/musenet/).

It's so convenient! probably make a lot of sense for a better audio experience (https://github.com/microlinkhq/sdk/issues/135)

**Comment by breadadams** [comment]
Do you think we should design some mockups/concepts for this @Kikobeats, or do you already have an idea of how you want it to look?
