### ISSUE TITLE
TypeError: Cannot read property 'color' of null

### ISSUE THREAD

**Issue by quintmouthaan** [microlinkhq/sdk#148]
## Bug Report

> You can use live code at Codesandbox: [React](https://codesandbox.io/s/n5w839zm4m) | [Vanilla](https://codesandbox.io/s/o92r2y4q9z)

**Current Behavior**
I user Microlink in my React project and am seeing the following error in my javascript console: TypeError: Cannot read property 'color' of null

**Expected behavior/code**
No error

**Possible Solution**
see screenshot for line of code that generates the error

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/39469362/62810878-c4a3b280-baff-11e9-8127-72c7d7eddb50.png)

I have a text area where the user can enter text with multiple links and I'm using the Microlink card in the following way:
![image](https://user-images.githubusercontent.com/39469362/62810918-ef8e0680-baff-11e9-8c31-c1032cb5a9c0.png)

**Comment by Kikobeats** [comment]
Thanks for reporting. Can you share the URL you are passing? I want to reproduce the error

**Comment by breadadams** [comment]
@Kikobeats I think I saw this same error when the quota runs out and a request fails.
