### ISSUE TITLE
Received `true` for a non-boolean attribute `loading`.

### ISSUE THREAD

**Issue by quintmouthaan** [microlinkhq/sdk#149]
## Bug Report

**Current Behavior**
I'm getting the following error in my javascript console: Received `true` for a non-boolean attribute `loading`.

**Possible Solution**
convert isLoading variable to a string
![image](https://user-images.githubusercontent.com/39469362/62811121-d20d6c80-bb00-11e9-9dbc-808afae33d43.png)

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/39469362/62811143-e3ef0f80-bb00-11e9-97c3-32b317bf9f8c.png)

**Comment by breadadams** [comment]
I'm pretty sure this is because `loading` is a valid html5 attribute, so styled-components is probably whitelisting it.

We could rename the property to `isLoading` @kikobeats

**Comment by Kikobeats** [comment]
More than that, we can destructuring the value and avoid pass it to children
