### ISSUE TITLE
Add an error UI state

### ISSUE THREAD

**Issue by breadadams** [microlinkhq/sdk#154]
## Feature Request

**Is your feature request related to a problem? Please describe.**

If the request fails the card shows up empty:

![image](https://user-images.githubusercontent.com/5795227/63304188-7e5e0880-c2e2-11e9-9c9a-8134ac51ad02.png)

**Describe the solution you'd like**
We should show some warning text telling the user it has failed, with an option to retry the request.

**Comment by roz0n** [comment]
Likewise, I'm curious if there's a way to test a failed request?

**Comment by breadadams** [comment]
It's on the roadmap @roz0n - all PRs are welcome though! 😄

**Comment by roz0n** [comment]
While I haven't looked at the source code... I think it might be possible to pass a function to the component that returns the request object that's currently throwing an error outside a catch block.

I'll give this a shot!

**Comment by Kikobeats** [comment]
A first approximation will be shipped in v5 🎉
