### ISSUE TITLE
Page freezing in Angular

### ISSUE THREAD

**Issue by spaduretu** [microlinkhq/sdk#171]
As i load microlink preview into my angular chat - project, as soon as i send an url message in my chat application, the preview should then be generated and rendered - actually this happens for the first sent url message, but then whole browser and page freezes and nothing can be done anymore. As long as no link is sent, everything works fine. I load the following libraries via cdn into my index.html
<br>

<script src="https://cdn.jsdelivr.net/combine/npm/react@16/umd/react.production.min.js,npm/react-dom@16/umd/react-dom.production.min.js,npm/styled-components@4/dist/styled-components.min.js,npm/@microlink/mql@latest/dist/mql.min.js,npm/@microlink/vanilla@latest/dist/microlink.min.js"></script>

**Comment by breadadams** [comment]
@spaduretu could you provide some basic repro code? In a codesandbox or similar. Thanks

**Comment by spaduretu** [comment]
@breadadams  i have created a sandbox project and uploaded the relevant components that illsutrate the code. Please understand, that i am completely new to this, so i do not really know how i could now share this sandbox project with you. I have logged in with my github account at sandbox but i dont know how i could share the link to this project with you. 
Is this the right way? 

[![Edit agitated-poincare-0nzwo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-poincare-0nzwo?fontsize=14&hidenavigation=1&theme=dark)

**Comment by spaduretu** [comment]
@breadadams seems that its working. 
So to explain the structure: 
In the **index.html** i have incnluded the cdn script for loading the right libraries (microlink) 

Than in **app.component** i have declared microlink as a const and defined in **AfterViewChanged** to look out for the "link-preview" class in any html (i have also tried to do this in message, or chatroom component. 

In **message.html** i have included the anchor tag (with class="link-preview") which should show the link preview.

The chatroom component consists of feed and chat-form (for text input). 
Whereas the feed component includes the messages

**Comment by breadadams** [comment]
Hi @spaduretu, sorry for the delayed response. I've checked out your repro but it doesn't seem to work for us:
![image](https://user-images.githubusercontent.com/5795227/73280803-55299880-41ef-11ea-822b-01a68980a183.png)

Nevertheless, we've created another Codesandbox of a basic Angular implementation of Microlink 👉 https://codesandbox.io/s/microlink-angular-example-6e4ie.

Check out the `card` component, you'll want to create something like this in your own project until our SDK provides a specific Angular package (hopefully sometime _soon_).

Feel free to let us know if you continue to have any issues, thanks!

**Comment by spaduretu** [comment]
hey @breadadams  and thanks for you reply! Unfortunately it still has the same behaviour / problem as i am using your solution. As soon as i am sending a link the whole application freezes! I did not put the whole application on sandbox the last time - maybe that why you got the error. But as i said - everything works fine - i even get the first preview , but as soon as i send the link, it appears and then the application freezes and nothing can be done anymore until i remove the preview in the html

**Comment by breadadams** [comment]
Hi @spaduretu,

> I did not put the whole application on sandbox the last time

Yeah that's probably a good idea, the codesandbox should ideally be a "minimalist" environment that just shows the precise issue. Maybe you could try creating another one?

Also, are you seeing any relevant error messages in your browser's console when the app freezes/crashes? This could help us in pinpointing your issue.

**Comment by spaduretu** [comment]
Yes, i just wanted to tell you , that i get the message from all "Subcomponents and the message component itself (where the actual message is rendered) 
ERROR TypeError: "this.card is undefined"
    ngAfterViewChecked message.component.ts:40
    Angular 31
    RxJS 5
    Angular 9

My Structure is as follows 

`<div class="mainContent">
  <div class="userListWrapper">
      <app-user-list> (User List Component)
      </app-user-list>
  </div>
  <div #scroller class="feedWrapper">
    <app-feed [showEmojiPicker]="showEmojiPicker"></app-feed> (Feed of Messages - Here i have a list of Message Components where the actual preview is inside)
  </div>
</div>

<div  class="chatFormWrapper">
  <app-chat-form (Chatform-Component) - This is the message input dialog 
      (emojiButtonPressed)="openEmojiMart($event)">
  </app-chat-form>
</div>`

**Comment by breadadams** [comment]
@spaduretu ok it looks like the issue lies within the `message.component`, and more specifically with the `this.card` ref. Are you creating the ref like in the example codesandbox I shared (`#card` on the html tag, etc)?

**Comment by spaduretu** [comment]
well - the thing is , i do not really understand what this code is all for and what would be the difference between my approach where i basically make `<a class="link-preview" href="{{link}}"...` and yours with the `<a #card [href]="url" [ngStyle]="style"....`. I used your ref as you wrote it but i honestly do not know what the option, card and style variables stand for and where they are being set- i did define them on the TS file but further on i really do not know what they are used for behind the scenes. Anyway, i really want to tell you that i appreciate your help :)

**Comment by spaduretu** [comment]
Anyway, as i am using my approach - with class=link-preview i do not get any errors in the console - but the application still freezes and has the same behaviour as by using your example

**Comment by spaduretu** [comment]
This is how the feed looks like as i post a link. So basically it works BUT after sending it - the application is freezed and i can hardly write any more messages because it seems to be in kind of an infinite loop or errors or idk what exactly causes this behaviour 
![example](https://user-images.githubusercontent.com/33127879/73556335-899b8f80-444f-11ea-91bd-47ee2a18ae48.jpg)

**Comment by breadadams** [comment]
@spaduretu 

> [...] and what would be the difference between my approach

So I'm not _that_ familiar with Angular, but with other ecosystems such as Vue and React to access a DOM element it's a standard to do so via a "ref" instead of a selector. This being because the library manages the DOM for you.

From what you've said so far I can't guess why the app would be freezing, it could be an issue with your implementation within the message component, or something elsewhere that's causing the component to re-render too often.

The only thing I can suggest at this point is that you create a "microlink-card" component (basically copying the `app/card` component from our [codesandbox](https://codesandbox.io/s/microlink-angular-example-6e4ie)) and importing that into message.

Otherwise, we're currently working on an angular package (https://github.com/microlinkhq/sdk/pull/182) with a similar implementation but that will be easier to consume than writing your own "card" component for each project.

**Comment by breadadams** [comment]
@spaduretu we now have an Angular SDK you can install, for more details see the docs: https://microlink.io/docs/sdk/integrations/angular

**Comment by spaduretu** [comment]
Hei, thanks a lot! Really aporeciate your support! I have clicked the link but unfortunately the link does not work.

**Comment by spaduretu** [comment]
> 
> 
> @spaduretu we now have an Angular SDK you can install, for more details see the docs: https://microlink.io/docs/sdk/integrations/angular

Her Bread, it me (again) ...well i have managed to get into the documentation and install the indicated NPM packages as instructed! 
Now unfortunately, as i try to compile my package - i get the following error 

```
ERROR in ./src/app/app.module.ts 64:13-22
"export 'default' (imported as 'Microlink') was not found in '@microlink/angular'
ERROR in ./node_modules/@microlink/angular/dist/fesm2015/microlink-angular.js 28:28-39
"export 'ɵɵloadQuery' was not found in '@angular/core'
i ｢wdm｣: Failed to compile.
    
    ERROR in node_modules/@microlink/angular/dist/microlink/microlink.component.d.ts(10,21): error TS2694: Namespace '"C:/Users/StefanPaduretu/Desktop/base-chat-master/node_modu
les/@angular/core/core"' has no exported member 'ɵɵFactoryDef
```

Seems like some library or anything else has not been exported ? Or did I do something wrong in this case?
