### ISSUE TITLE
Ensure to log fetch errors

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/sdk#174]
If fetch failed, there is not an easy way to report the error:
https://github.com/microlinkhq/sdk/blob/c4d87f30fc8753ece38b64f69eeb18c0596091d6/packages/react/src/index.js#L88

Need to add the logic necessary to make easy report any kind of error, linking the repository with the error

**Comment by breadadams** [comment]
I think you can tie this in with the context PR here: https://github.com/microlinkhq/sdk/pull/169/files#diff-8caae6eaf0ff9059e6b6a883d6117a2aR70

**Comment by Kikobeats** [comment]
done at https://github.com/microlinkhq/sdk/commit/d13c967d9aa8016f9fb0dca72490571c30b0d749
