### ISSUE TITLE
microlink.io is down?

### ISSUE THREAD

**Issue by adivincenzo** [microlinkhq/sdk#178]
## Bug Report

> You can use live code at Codesandbox: [React](https://codesandbox.io/s/n5w839zm4m) | [Vanilla](https://codesandbox.io/s/o92r2y4q9z)

**Current Behavior**

When I try to visit microlink.io in my browser I get a response that "microlink.io's server IP address could not be found." Also, when I try to render a microlink in my react project I get a 500 response. This is happening in version 4.4.1 and 5.0.0.

**Expected behavior/code**

I expect to be able to access microlink.io and I expect that I will get a success response when trying to render any url I've used in the past (e.g., www.google.com, www.yahoo.com).

**Additional context/Screenshots**

<img width="1128" alt="Screen Shot 2020-01-21 at 9 35 18 AM" src="https://user-images.githubusercontent.com/33606398/72818597-5d069d00-3c31-11ea-9f3c-2860eb0d077a.png">
<img width="1192" alt="Screen Shot 2020-01-21 at 9 35 53 AM" src="https://user-images.githubusercontent.com/33606398/72818659-7576b780-3c31-11ea-8f9a-3d9e069d4535.png">

**Comment by Kikobeats** [comment]
Hello 🙂

You can see the status of every service behind Microlink infrastructure at https://status.microlink.io.

Looks it wasn't down on the timestamp this issue was created.

Maybe was a little failover of your internet connection or your DNS resolver?
