### ISSUE TITLE
Make embeds clickable while loading

### ISSUE THREAD

**Issue by chasemccoy** [microlinkhq/sdk#203]
## Feature Request
When blocks embedded with the React SDK are loading, they are not clickable at all. Since the link is presumably known, these could be clickable so that you don't have to wait for it to finish loading before following the link.

**Comment by Kikobeats** [comment]
Hello, this looks an old thing because links are clickable event they are loading 

https://storybook.microlink.io/?path=/story/props--loading

🙂
