### ISSUE TITLE
[vue] Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by razbakov** [microlinkhq/sdk#230]
## Bug Report

I created [Codesandbox](https://codesandbox.io/s/gracious-breeze-quodl?file=/src/App.vue) but it works without problem.

**Current Behavior**

Locally I have error message in console:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Card (created by GlobalState)
    in GlobalState (created by Microlink)
    in Microlink
```

**Possible Solution**

Found [here](https://github.com/material-components/material-components-web-react/issues/434) same bug

**Comment by Kikobeats** [comment]
@razbakov

I think this is a thing related with React lifecycle that eventually you see cause it was wrong on the React codebase.

It should be work fine now – just confirm to me, otherwise we can try to triage  what's happening 🙂
