### ISSUE TITLE
it fails for some websites that need to accept cookies

### ISSUE THREAD

**Issue by S-codes14** [microlinkhq/sdk#256]
## Bug Report

`<Microlink
    url='https://youtu.be/S9klw-psnaU?list=OLAK5uy_kzi432wdNqi3PRiV1Gag3oxX_bo45n8ww'
    autoPlay={false}
    media='video'
    muted={false}
    controls
    loop={false}
  /> `

**Current Behavior**
it is just showing the youtube logo, but when you click on the preview it does redirect to the desired url

**Expected behavior/code**
I expected the code to run properly and show the video preview

**Additional context/Screenshots**
![failed](https://user-images.githubusercontent.com/81442054/126888082-453b36de-e810-4d7f-8684-0c6b30ef7a64.png)

**Comment by breadadams** [comment]
@Kikobeats this is probably to do with the need to accept their terms/cookies/whatever when you land on the video.

I know the same was happening on iMessage a few months ago, and they fixed it somehow (maybe with Apple powers... 😅).

**Comment by Kikobeats** [comment]
I think so :(

![CleanShot 2021-07-25 at 11 27 56@2x](https://user-images.githubusercontent.com/2096101/126894396-5c7ee2c7-afd9-482d-99f1-b023d6d1fec2.png)

**Comment by S-codes14** [comment]
> I think so :(
> 
> ![CleanShot 2021-07-25 at 11 27 56@2x](https://user-images.githubusercontent.com/2096101/126894396-5c7ee2c7-afd9-482d-99f1-b023d6d1fec2.png)
> 
> This is a thing that should be handled by Microlink API. In fact, the API resolves most of the cookie banners implemented on-site. What is happening here is the workflow is different (it redirects you an URL, you should accept, then redirect it again).
> 
> I need to explore a bit the solution; any feedback about that is very welcome!

Should i close the issue or leave it open, on my side it is okay as long as the user gets redirected to the correct url i am happy, just thought i should let you know

**Comment by Kikobeats** [comment]
let me keep it open to tracking the progress of this. Thanks for opening it 🙂

**Comment by Kikobeats** [comment]
resolved at API level
