### ISSUE TITLE
Crashed with invalid link

### ISSUE THREAD

**Issue by alnidok** [microlinkhq/sdk#283]
## Bug Report

> You can use live code at Codesandbox: [React](https://codesandbox.io/s/microlink-react-forked-rnpyqv) | [Vanilla](https://codesandbox.io/s/microlink-vanilla-forked-xlxm59)

**Current Behavior**

I have text with link and I want to preview this link. JS crash if link is invalid or broken or something else.
There are examples in sandbox above.

It happens because endpoint https://api.microlink.io/?url=https://invalid-link returns `"<required> an URL for getting content."` in data.url. 
https://github.com/microlinkhq/sdk/blob/4a6e04fc231ac8cc7f3d9c04445e2acaf80cc426/packages/react/src/components/Card/CardContent.js#L17
`new URL('<required> an URL for getting content.')` throw error.

**Expected behavior/code**
Preview won't show but without crash.

**Comment by Kikobeats** [comment]
Hello, and thanks a lot for reporting.

I improved this behavior at Microlink API:

https://api.microlink.io/?url=https://invalid-link

It returns now a proper error – can you check at your code level? it's now working as expected?

**Comment by alnidok** [comment]
Better but there is a problem with method `fetchFromApi` (@microlink/mql)
debug: http://dl3.joxi.net/drive/2022/05/27/0014/0289/966945/45/6b73c3a60b.png
error: http://dl4.joxi.net/drive/2022/05/27/0014/0289/966945/45/259b3676f1.png

**Comment by Kikobeats** [comment]
Thanks a lot for taking care about this 🙏

I released `@microlink/mql@0.10.20` that address the issue.

Also, created a tiny playground to make easy reproduce errors in the future:
https://mql.microlink.io/?url=https://invald-url

If you just remove `node_modules` and install again, the new version should be there; can you confirm? 🙂

**Comment by alnidok** [comment]
Yes, now it works good. Thank you!
