### ISSUE TITLE
Cors on any link

### ISSUE THREAD

**Issue by SolAleksander** [microlinkhq/sdk#287]
Hello. This problem
![image](https://user-images.githubusercontent.com/29248079/178112675-490473a8-48fd-41b4-ab78-25444b08fc7e.png)

And your dependencie [microlink/mql](https://www.npmjs.com/package/%40microlink%2Fmql)
started demanding url-http package, which was not required before
I had to install it in my dependencies and resolve the path to it. This has never happened before
Today I updated webpack packages and this moment happened on the dev assembly.
But I haven’t uploaded anything to production yet, but there is a bug.
Maybe mql is the reason

Thank you

**Comment by Kikobeats** [comment]
Hello,

It isn't a CORS error. The real error is being hidden, and the browser is treated it as CORS at the very last, so we need to go deep and see what's happening behind that.

Can wrap the code with `try/catch` and try to log the error there?

Also, what's SDK are you using? React? Vanilla?

Both are using [@microlink/mql that is using url-http is dependency](https://github.com/microlinkhq/mql/blob/master/package.json#L49=). It isn't clear to me why you have to install it; npm install should resolve the dependency tree.
