### ISSUE TITLE
Upgrade microlink react SDK Styled-Component Package

### ISSUE THREAD

**Issue by gbourne1** [microlinkhq/sdk#326]
An error occurs when installing the https://www.npmjs.com/package/@microlink/react package due to module incompatibilities with Styled-Component package on React 18.

<img width="583" alt="Screenshot 2023-11-29 at 11 30 02 AM" src="https://github.com/microlinkhq/open/assets/13002533/7d44266d-5938-4c46-a367-050abfd09b7b">

This occurs when you have style-components 6^ included in your main React app.

**Comment by Kikobeats** [comment]
Fixed in v5.5.16 🙂
