### ISSUE TITLE
Instagram links aren't fetching

### ISSUE THREAD

**Issue by coffeewithdonut** [microlinkhq/sdk#373]
## Bug Report

**Current Behavior**

Within the last few days, all Instagram posts have been intercepted with a login page instead of returning the content.

Test – https://microlink.io/sdk?url=https%3A%2F%2Fwww.instagram.com%2Fp%2FC8hIungMPmD

I've tried tweaking prerendering, devices, and video/audio with no success.

**Comment by Kikobeats** [comment]
Hello, one way to escape from the Instagram wall is to pass your own proxy server:
https://microlink.io/docs/api/parameters/proxy

Another way could be pass your authentication cookies via headers:
https://microlink.io/docs/api/parameters/headers

**Comment by coffeewithdonut** [comment]
We're using the pro endpoint, to quote your documentation:

> We provide an automatic proxy resolution included for any [pro plan](https://microlink.io/docs/api/basics/endpoint) to handle IP blocking, CAPTCHAs, banners, or any other scraping shield protection.

I think it's a bug, Instagram is a biggie

**Comment by Kikobeats** [comment]
Hello, 

Happy to share we improved the Instagram support:

![CleanShot 2024-07-07 at 21 46 19@2x](https://github.com/microlinkhq/sdk/assets/2096101/833f8989-3127-4299-8019-179d6b301e2d)

However, still you can experience some instability behavior. Instagram is applying very aggressive rules to access to content. In the past, if you try to consume the content from a mobile phone, even you are not logged, you can do it. Doing this these days is hard: the Instagram WAF forces you to login after a few requests. We're doing our best effort to don't abuse Instagram and returns metadata from Instagram links.
