### ISSUE TITLE
import styled from styled-components issue

### ISSUE THREAD

**Issue by darraghoriordan-skedsocial** [microlinkhq/sdk#376]
## Questions & Answers

Hey I have an issue but no one else has reported it so i assume it's something in my configuration. But in the @microlink/vanilla packages you `import { css, styled, keyframes } from 'styled-components';`. My webpack, and the built/output from webpack, complains that there is no named `styled` export from styled-components which is correct according to the styled-components package at latest v5 version.

I'm just wondering how no-one else gets this issue? It seems like it would affect anyone using latest v5 or higher, Is there a way to override this or something? 

I'm using

```
  "@microlink/react": "5.5.22",
    "@microlink/vanilla": "5.5.22",
     "styled-components": "5.3.11",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
```

These are the named exports according to styled-components built-in types:

![image](https://github.com/user-attachments/assets/d076f082-5aa3-4e69-9c15-e57dc7ee0c4d)

(I think that) The correct imports would be `import styled, { css, keyframes } from 'styled-components';`

here is the webpack error

```
WARNING in ./node_modules/@microlink/vanilla/dist/microlink.mjs 1136:17-23
export 'styled' (imported as 'styled') was not found in 'styled-components' (possible exports: ServerStyleSheet, StyleSheetConsumer, StyleSheetContext, StyleSheetManager, ThemeConsumer, ThemeContext, ThemeProvider, __PRIVATE__, createGlobalStyle, css, default, isStyledComponent, keyframes, useTheme, version, withTheme)
 @ ./public/components/webpack.vendors.js 571:19-48
```

**Comment by Kikobeats** [comment]
Hello,

For using the vanilla version, you need to provide `style-components` as external dependency.

Check the markup of this website: https://sdk-vanilla.microlink.io/

**Comment by Kikobeats** [comment]
closing for now unless the user report more stuff to investiage
