### ISSUE TITLE
Websites think it's a bot

### ISSUE THREAD

**Issue by GitFlip** [microlinkhq/sdk#377]
## Questions & Answers

**Context of your question**
I'm using the Microlink SDK for React and every now and then, some sites think that the preview fetching is being done by bots and require a bot check. Is there a way to prevent this?

Here's a screenshot for example of an amazon preview with the issue:
![image](https://github.com/user-attachments/assets/5f05fe7a-27ae-4dd9-baae-c980092935d1)

**Comment by Kikobeats** [comment]
Thanks for reporting!

Amazon is quite massive and they have ways of detecting and verifying where the traffic is coming from.

Unfortunately there is not much we can do. If this is a think you really want to need to be done, I recommend you to use a third party proxy server and pass the proxy tunnel against Microlink https://microlink.io/docs/api/parameters/proxy
