### ISSUE TITLE
[Feat] Customizable Preview Components

### ISSUE THREAD

**Issue by Karunika** [microlinkhq/sdk#378]
## Feature Request

First things first, this library is amaing as is, so kudos to the developers.

However, I am using Joy UI, and I want to use their pre-made components to match the ui of the rest of my page. Is it possible to add the possibility of adding customizable components?

**Comment by Kikobeats** [comment]
Hello,

You can customize the component easily using vanilla and old CSS 🙂

Check this documentation! https://microlink.io/docs/sdk/getting-started/styling

**Comment by Karunika** [comment]
Hi, thank you so much for your reply!

I have noticed that css can be used for customization purposes which is great!

I was wondering if we can use full blown React Components as a replacement to the base Components?

**Comment by breadadams** [comment]
Not sure if it's directly related but we started looking into something potentially similar a while ago in the following PR:

- https://github.com/microlinkhq/sdk/pull/278

**Comment by Kikobeats** [comment]
@Karunika I'm preparing something, let me update you asap!

**Comment by Karunika** [comment]
Thank you so much, I really appreciate it :D

But do feel free to take your time, cause I, personally, do not need this feature urgently :)
