### ISSUE TITLE
List of integrations

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/sdk#41]
This issue is an open track list of frontend side libraries for make easier microlink integration.

Feel free to discuss or suggest 😄

Two points here:

- The goal is to have the same API and default styling across all the libraries. This probably means that we need to extract core logic into a separate package that we can use across the integrations, like the [logic used for creating the API request](https://github.com/microlinkhq/microlinkjs/blob/master/packages/react-microlink/src/index.js#L11). It's early to think about that but just keeps in mind. 

- Would be nice assign specific contributor to maintain each specific integration. Ideally, move of the logic out of the integration to be this task simple and easier.

## List of integrations

- [x] [React](https://github.com/microlinkhq/sdk/tree/master/packages/react) (@kikobeats / @breadadams)
- [x] [Vanilla JS](https://github.com/microlinkhq/sdk/tree/master/packages/vanilla) (@kikobeats)
- [x] [Vue](https://github.com/microlinkhq/sdk/tree/master/packages/vue) (@breadadams)
- [x] [AngularJS](https://github.com/microlinkhq/sdk/tree/master/packages/angular) (@breadadams)
- [ ] [WordPress Plugin](https://github.com/microlinkhq/wordpress) (@jontorrado) 
- [ ] Polymer
- [ ] React-native
- [ ] [Ghost](https://github.com/TryGhost/Ghost/blob/fbb60adde73e2c5afa1490c2dd1f12c51a95eb9a/content/apps/README.md)
- [ ] Gatsby Plugin
- [ ] *add-your-hype-library-slash-framework-here*

## A note about vanilla/umd

Vanilla bundle is a little special. Currently it's a bundle of the `react-microlink` component. The size is a little heavy (~50kb) because it needs `react-dom` as dependency.

Probably, using something lightweight like `vuejs` we can improve the bundle. 

Also I tried to switch from `react` to `preact` in the build process. Currently is not possible because we are using `Fragment`from react API and it is not supported by preact.

**Comment by breadadams** [comment]
Bagsy WP integration! 🖐

**Comment by Kikobeats** [comment]
I'm going to mention @alexjoverm and @jroji 😄

**Comment by deadcoder0904** [comment]
Gatsby Plugin would be much better for directly showing link previews in Blog Posts

**Comment by breadadams** [comment]
Good idea @deadcoder0904, we're happy to receive a PR if you're up for it 🙂

**Comment by deadcoder0904** [comment]
Never made one actually so have to learn. But I'll do it when I make a blog with your help :)

**Comment by Kikobeats** [comment]
@deadcoder0904 sure! I added it into the list 🙂

**Comment by Kikobeats** [comment]
A new page has been shipped for visualizing all the integrations available: https://microlink.io/integrations
