### ISSUE TITLE
Unnecessary props passed to DOM

### ISSUE THREAD

**Issue by breadadams** [microlinkhq/sdk#95]
![image](https://user-images.githubusercontent.com/5795227/37868758-0d033c66-2fac-11e8-981b-2f3d7cc38700.png)

Some props are leaking through to the DOM (unnecessarily) ☝️ (`autoplay`, `controls`, etc)

**Comment by Kikobeats** [comment]
I know, but I consider the effort to remove it implies more cost than simply pass it

what do you think?

**Comment by breadadams** [comment]
Yeah I had a quick go at it and gave up quickly 😅 

I was thinking we could create a small util. method, where we pass `props` & the keys of props we want to exclude from a return object. Eg:

```jsx
const propCleaner = (obj, excludeKeys) => {
  const objKeys = Object.keys(obj)

  return objKeys.reduce((acc, key) => {
    return !excludeKeys.include(key) && acc[key] = obj[key]
  })
}
 
<Component {...propCleaner(...props, ['apiKey', 'autoPlay')} />
```

**Comment by breadadams** [comment]
Yep that seems to do basically what I was suggesting.

We'll have to see how the size looks with it included - https://bundlephobia.com/result?p=clean-tag@1.0.4

**Comment by Kikobeats** [comment]
I would not worry unless it represents a problem

The cost of add 11kb extra size into the library vs 0kb, also not logic for handle this 🙂

**Comment by breadadams** [comment]
Just came across [this](https://github.com/airbnb/react-dates/blob/master/examples/SingleDatePickerWrapper.jsx#L104) @Kikobeats. Lodash's omit should do the trick.

I think we **should** implement this as we're generating slightly _unsemantic_ markup, passing "media" attributes (autoplay, etc) to DOM elements that shouldn't receive them.

**Comment by Kikobeats** [comment]
Another one: https://github.com/marionebl/dom-to-svg
